GET /test
Host: localhost:8082
Accept: application/json

###

GET /api/admin/members/testId
Host: localhost:8082
Accept: application/json

###

GET /api/admin/members
Host: localhost:8082
Accept: application/json

###

POST /api/service/members/sign-up
Host: localhost:8082
Content-Type: application/json

{
  "membershipNo": 428,
  "memberStatusNo": 392,
  "memberId" : "user7",
  "nickname" : "유저7",
  "name" : "유저7",
  "isMan": 1,
  "birth": "2019-12-14T07:51:01",
  "password": "1234",
  "phoneNumber": "010-6703-0112",
  "email": "use339d5@test1.com"
}

###
GET /api/service/members/sign-up/memberId/user4
Host: localhost:8082
Accept: application/json
