POST localhost:8082/api/admin/products
content-type: application/json

{
     "productNo" : 0,
     "name" : "객체지향의 사실과 오해",
     "simpleDescription" : "객체지향이란 무엇인가? 이 책은 이 질문에 대한 답을 찾기 위해 노력하고 있는 모든 개발자를 위한 책이다.",
     "detailsDescription" : "상세 설명",
     "stock" : 0,
     "isSelled" : true,
     "isForceSoldOut" : false,
     "thumbnailUrl" : "testUrl",
     "fixedPrice" : 20000,
     "increasePointPercent" : 1,
     "discountPercent" : 10,
     "rawPrice" : 12000
}